# Generated by Django 3.0.4 on 2020-04-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20200401_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='last_active',
            field=models.DateTimeField(null=True),
        ),
    ]
